name: Test Workflow

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run npm build
        run: |
          echo "Running npm build..."
          npm install
          npm run build
