name: Test Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run npm build
        run: echo "Running npm legit workflow..."

